"""
Centralized language definitions for the translation pipeline.

Source languages are based on Speechmatics ASR support.
Target languages are based on DeepL translation API support.
"""

# ---------------------------------------------------------------------------
# Source languages – Speechmatics ASR
# ---------------------------------------------------------------------------
# code → display name (matches frontend sourceLanguages)
SOURCE_LANGS = {
    "ar": "Arabic",
    "ba": "Bashkir",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bg": "Bulgarian",
    "yue": "Cantonese",
    "ca": "Catalan",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "gl": "Galician",
    "de": "German",
    "el": "Greek",
    "he": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "id": "Indonesian",
    "ia": "Interlingua",
    "ga": "Irish",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "ms": "Malay",
    "en_ms": "Malay & English",
    "mt": "Maltese",
    "cmn": "Mandarin",
    "cmn_en": "Mandarin & English",
    "cmn_en_ms_ta": "Mandarin Malay Tamil & English",
    "mr": "Marathi",
    "mn": "Mongolian",
    "no": "Norwegian",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sw": "Swahili",
    "sv": "Swedish",
    "tl": "Tagalog & English",
    "ta": "Tamil",
    "en_ta": "Tamil & English",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "ug": "Uyghur",
    "vi": "Vietnamese",
    "cy": "Welsh",
}

# ---------------------------------------------------------------------------
# Target languages – DeepL translation API
# ---------------------------------------------------------------------------
# display name → DeepL target code
#
# Languages are split into two tiers:
#   - Standard: support latency_optimized model, formality, and glossaries
#   - Quality-only (*): only work with quality_optimized model (or no model
#     specified). They do NOT support formality or glossaries.

TARGET_LANG_MAP = {
    # --- Standard languages (latency_optimized OK) ---
    "Arabic": "AR",
    "Bulgarian": "BG",
    "Chinese (Simplified)": "ZH-HANS",
    "Chinese (Traditional)": "ZH-HANT",
    "Czech": "CS",
    "Danish": "DA",
    "Dutch": "NL",
    "English": "EN-US",
    "English (British)": "EN-GB",
    "Estonian": "ET",
    "Finnish": "FI",
    "French": "FR",
    "German": "DE",
    "Greek": "EL",
    "Hebrew": "HE",
    "Hungarian": "HU",
    "Indonesian": "ID",
    "Italian": "IT",
    "Japanese": "JA",
    "Korean": "KO",
    "Latvian": "LV",
    "Lithuanian": "LT",
    "Norwegian": "NB",
    "Polish": "PL",
    "Portuguese (Brazilian)": "PT-BR",
    "Portuguese (European)": "PT-PT",
    "Romanian": "RO",
    "Russian": "RU",
    "Slovak": "SK",
    "Slovenian": "SL",
    "Spanish": "ES",
    "Spanish (Latin American)": "ES-419",
    "Swedish": "SV",
    "Thai": "TH",
    "Turkish": "TR",
    "Ukrainian": "UK",
    "Vietnamese": "VI",
    # --- Quality-only languages (* in DeepL docs) ---
    "Acehnese": "ACE",
    "Afrikaans": "AF",
    "Albanian": "SQ",
    "Aragonese": "AN",
    "Armenian": "HY",
    "Assamese": "AS",
    "Aymara": "AY",
    "Azerbaijani": "AZ",
    "Bashkir": "BA",
    "Basque": "EU",
    "Belarusian": "BE",
    "Bengali": "BN",
    "Bhojpuri": "BHO",
    "Bosnian": "BS",
    "Breton": "BR",
    "Burmese": "MY",
    "Cantonese": "YUE",
    "Catalan": "CA",
    "Cebuano": "CEB",
    "Croatian": "HR",
    "Dari": "PRS",
    "Esperanto": "EO",
    "Galician": "GL",
    "Georgian": "KA",
    "Guarani": "GN",
    "Gujarati": "GU",
    "Haitian Creole": "HT",
    "Hausa": "HA",
    "Hindi": "HI",
    "Icelandic": "IS",
    "Igbo": "IG",
    "Irish": "GA",
    "Javanese": "JV",
    "Kapampangan": "PAM",
    "Kazakh": "KK",
    "Konkani": "GOM",
    "Kurdish (Kurmanji)": "KMR",
    "Kurdish (Sorani)": "CKB",
    "Kyrgyz": "KY",
    "Latin": "LA",
    "Lingala": "LN",
    "Lombard": "LMO",
    "Luxembourgish": "LB",
    "Macedonian": "MK",
    "Maithili": "MAI",
    "Malagasy": "MG",
    "Malay": "MS",
    "Malayalam": "ML",
    "Maltese": "MT",
    "Maori": "MI",
    "Marathi": "MR",
    "Mongolian": "MN",
    "Nepali": "NE",
    "Occitan": "OC",
    "Oromo": "OM",
    "Pangasinan": "PAG",
    "Pashto": "PS",
    "Persian": "FA",
    "Punjabi": "PA",
    "Quechua": "QU",
    "Sanskrit": "SA",
    "Serbian": "SR",
    "Sesotho": "ST",
    "Sicilian": "SCN",
    "Sundanese": "SU",
    "Swahili": "SW",
    "Tagalog": "TL",
    "Tajik": "TG",
    "Tamil": "TA",
    "Tatar": "TT",
    "Telugu": "TE",
    "Tsonga": "TS",
    "Tswana": "TN",
    "Turkmen": "TK",
    "Urdu": "UR",
    "Uzbek": "UZ",
    "Welsh": "CY",
    "Wolof": "WO",
    "Xhosa": "XH",
    "Yiddish": "YI",
    "Zulu": "ZU",
    # --- Backward-compatibility aliases ---
    "Chinese": "ZH-HANS",
}

# DeepL codes that support the latency_optimized model
LATENCY_SUPPORTED_LANGS: set[str] = {
    "AR", "BG", "CS", "DA", "DE", "EL", "EN", "EN-GB", "EN-US",
    "ES", "ES-419", "ET", "FI", "FR", "HE", "HU", "ID", "IT",
    "JA", "KO", "LT", "LV", "NB", "NL", "PL", "PT", "PT-BR",
    "PT-PT", "RO", "RU", "SK", "SL", "SV", "TH", "TR", "UK",
    "VI", "ZH", "ZH-HANS", "ZH-HANT",
}

# DeepL codes that support the formality parameter (same as latency set)
FORMALITY_SUPPORTED_LANGS: set[str] = LATENCY_SUPPORTED_LANGS

# DeepL codes that support custom_instructions
CUSTOM_INSTRUCTION_LANGS: set[str] = {
    "DE", "EN", "EN-GB", "EN-US", "ES", "ES-419",
    "FR", "IT", "JA", "KO", "ZH", "ZH-HANS", "ZH-HANT",
}

# ---------------------------------------------------------------------------
# Source ↔ Target overlap mappings
# ---------------------------------------------------------------------------
# Maps a Speechmatics source code to the DeepL target display name it
# corresponds to.  Used to disable same-language source/target combos.

SOURCE_CODE_TO_TARGET_NAME: dict[str, str | list[str]] = {
    "ar": "Arabic",
    "ba": "Bashkir",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bg": "Bulgarian",
    "yue": ["Cantonese", "Chinese (Simplified)", "Chinese (Traditional)"],
    "ca": "Catalan",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": ["English", "English (British)"],
    "eo": "Esperanto",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "gl": "Galician",
    "de": "German",
    "el": "Greek",
    "he": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "ms": "Malay",
    "mt": "Maltese",
    "cmn": ["Chinese (Simplified)", "Chinese (Traditional)"],
    "mr": "Marathi",
    "mn": "Mongolian",
    "no": "Norwegian",
    "fa": "Persian",
    "pl": "Polish",
    "pt": ["Portuguese (Brazilian)", "Portuguese (European)"],
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": ["Spanish", "Spanish (Latin American)"],
    "sw": "Swahili",
    "sv": "Swedish",
    "tl": "Tagalog",
    "ta": "Tamil",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "cy": "Welsh",
}

# Reverse: target display name → list of Speechmatics source codes
TARGET_NAME_TO_SOURCE_CODES: dict[str, list[str]] = {}
for _code, _names in SOURCE_CODE_TO_TARGET_NAME.items():
    if isinstance(_names, str):
        _names = [_names]
    for _name in _names:
        TARGET_NAME_TO_SOURCE_CODES.setdefault(_name, []).append(_code)
